Bundle mo files, and remove build step

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,3 +17,12 @@ script:
       rustup component add clippy
       cargo clippy --verbose
     fi
+  - |
+    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
+      ./msgfmt.sh
+      if [ -n "$(git status -s)" ]; then
+        echo "If this fails, the lang/*.mo files are out of date."
+        echo "Run ./msgfmt.sh to fix this."
+        exit 1
+      fi
+    fi
